[package]
name = "settings-asus"
version = "1.0.0"
description = "ASUS laptop controls for Settings"
license = "MIT"
authors = ["Ken Smith"]
edition = "2024"

[dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
toml = "1.1.6"

[profile.release]
lto = "thin"
strip = true
