[package]
name = "settings-corsair"
version = "1.0.1"
description = "Corsair keyboards for Settings"
license = "MIT"
authors = ["Ken Smith"]
edition = "2024"

[dependencies]
anyhow = "1.0.104"
libc = "0.2"
serde_json = { version = "1.0.151", features = ["preserve_order"] }

[profile.release]
lto = "thin"
strip = true
